import os

LINE_CHANNEL_SECRET = os.getenv('CHANNEL_SECRET')
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('CHANNEL_ACCESS_TOKEN')

WEATHER_API_KEY = os.getenv('WEATHER_API_KEY')
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')
AI_API_KEY = os.getenv('AI_API_KEY')